version: 0.2

#run-as: Linux-user-name

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
 
phases:
  install:
    #run-as: Linux-user-name
    #on-failure: ABORT | CONTINUE | RETRY | RETRY-count | RETRY-regex | RETRY-count-regex
    runtime-versions:
      python: 3.11
    
  pre_build:
    #run-as: Linux-user-name
    #on-failure: ABORT | CONTINUE | RETRY | RETRY-count | RETRY-regex | RETRY-count-regex
    commands:
      - echo "Logging into Docker Hub..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - echo "Login Successful"
      - pip install -r day-14/simple-python-app/requirements.txt
    #finally:
      #- command
      #- command
    
  build:
    #run-as: Linux-user-name
    #on-failure: ABORT | CONTINUE | RETRY | RETRY-count | RETRY-regex | RETRY-count-regex
    commands:
      - cd day-14/simple-python-app
      - echo "Building Docker image"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
    
  post_build:
    #run-as: Linux-user-name
    #on-failure: ABORT | CONTINUE | RETRY | RETRY-count | RETRY-regex | RETRY-count-regex
    commands:
      - echo "Build is successful"
